# Generated by Django 5.0.2 on 2024-03-12 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_poc_name_hotel_poc_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.type'),
        ),
    ]
