# Generated by Django 5.0.2 on 2024-03-14 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_hotel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.type'),
        ),
    ]
