# Generated by Django 5.0.2 on 2024-04-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_rename_room_booking_roombooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='ac',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='bathroom_attached',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
