# Generated by Django 5.0.2 on 2024-04-16 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_room_ac_alter_room_bathroom_attached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hotel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
    ]
