# Generated by Django 5.0.2 on 2024-04-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_room_hotel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hotel_name',
            field=models.CharField(max_length=50),
        ),
    ]
