# Generated by Django 5.0.2 on 2024-04-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_room_hotel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='end_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roombooking',
            name='start_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
