# Generated by Django 5.0.2 on 2024-05-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_alter_room_ac_alter_room_bathroom_attached'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='room',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
