# Generated by Django 5.0.2 on 2024-04-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0002_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
