# Generated by Django 5.0.2 on 2024-04-13 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('prefix', models.CharField(max_length=10)),
                ('points', models.IntegerField()),
                ('price', models.IntegerField()),
                ('multiple_factor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoyalPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveler', models.CharField(max_length=50)),
                ('card_points_remain', models.IntegerField()),
                ('earned_points_remain', models.IntegerField()),
                ('points_remain', models.IntegerField()),
                ('points_redeemed', models.IntegerField()),
                ('total_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('total_points', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.cardtype')),
            ],
        ),
    ]
