# Generated by Django 5.0.2 on 2024-04-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltycard',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
