# Generated by Django 5.0.2 on 2024-04-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_alter_loyaltycard_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyalpoint',
            name='card_points_remain',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loyalpoint',
            name='earned_points_remain',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loyalpoint',
            name='points_redeemed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loyalpoint',
            name='points_remain',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loyalpoint',
            name='total_points',
            field=models.IntegerField(null=True),
        ),
    ]
