# Generated by Django 5.0.2 on 2024-04-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_alter_loyalpoint_card_points_remain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltycard',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
