# Generated by Django 5.0.2 on 2024-04-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_loyaltycard_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltycard',
            name='days_remain',
            field=models.IntegerField(default=56),
            preserve_default=False,
        ),
    ]
