# Generated by Django 5.0.2 on 2024-04-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_loyaltycard_days_remain'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltycard',
            name='current_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='days_remain',
            field=models.IntegerField(default=0),
        ),
    ]
