# Generated by Django 5.0.2 on 2024-04-17 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0007_rename_card_points_remain_loyalpoint_card_points_purchased'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loyalpoint',
            old_name='earned_points_remain',
            new_name='earned_points',
        ),
    ]
