# Generated by Django 5.0.2 on 2024-04-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_taxi_admin_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxi',
            name='daily_rent',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxi',
            name='km_charge',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
