# Generated by Django 5.0.2 on 2024-04-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_taxi_available_taxi_daily_rent_taxi_km_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
