# Generated by Django 5.0.2 on 2024-04-17 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_alter_taxi_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveler_name', models.CharField(max_length=50)),
                ('pickup_location', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_rent', models.IntegerField()),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.taxi')),
            ],
        ),
    ]
