# Generated by Django 5.0.2 on 2024-03-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_item_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='restaurant_name',
            field=models.CharField(default='rest', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='restaurant_name',
            field=models.CharField(default='rest', max_length=100),
            preserve_default=False,
        ),
    ]
