# Generated by Django 5.0.2 on 2024-04-16 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_combo_restaurant_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=50)),
                ('traveler_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.combo')),
            ],
        ),
    ]
