# Generated by Django 5.0.2 on 2024-04-18 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_combobooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='combobooking',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='combobooking',
            name='food_date',
            field=models.DateField(default='2024-04-20'),
            preserve_default=False,
        ),
    ]
